name: 'GitHub Action for Codepush - MK'
author: 'Marvin Kome'
description: 'Wraps the appcenter CLI to enable common commands.'
inputs:
  directory:
    default: .
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory }}
